#!/usr/bin/env bash
#
# Alias for gradlew.  Used for development.  It starts
# the gradle daemon which should only be used
# when developing.
#
# Example:  ./gw clean build -x test
#
# Make script executable: chmod +x gw
#


./gradlew --daemon -q -Pencrypt_key=$IAT_DEPLOY_SECRET_KEY $@

chmod 755 ./dist/*.sh