###########################################################
# Default
###########################################################
spring:
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: true
  http:
    multipart:
      location: "${java.io.tmpdir}"
      maxFileSize: "10MB"
  redis:
      host: "@REDIS_HOST@"

logging:
  level:
    org:
      opentestsystem:
        ap:
          common: "info"
      springframework:
        cloud:
          config:
            client: "warn"

management:
  security:
    roles: "ADMIN"

itembank:
  host: "@GITLAB_HOST@"
  group: "@GITLAB_GROUP@"
  accessToken: "{cipher}@GITLAB_ACCESS_TOKEN@"
  user: "@GITLAB_USER@"
  password: "{cipher}@GITLAB_PASSWORD@"
  localBaseDir: "${HOME}/ItemBank"
  apiVersion: "/api/v4"
  bankKey: "187"
  lockSectionMaxRetries: "10"
  lockSectionRetryDelayMillis: "2000"

tasks:
  itemCleanupThresholdMillis : "600000"
  itemCleanupRunEveryMillis: "600000"

