apiVersion: v1
kind: PersistentVolume
metadata:
  name: iat-efs-report-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: @AWS_EFS_REPORT_DNS_NAME@
    path: "/"
